[package]
name = "euler_843_bis"
version = "0.1.0"
edition = "2021"

[features]

implementation_one = []
implementation_two = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.7.0"
